#!/usr/bin/env python3
"""AEP schema registry -> generated SDK types.

Reads   schemas/aep-event.schema.json, schemas/registry/*.json, schemas/types/*.schema.json
Emits   schemas/gen/ts/aep-types.ts        (TypeScript)
        schemas/gen/python/aep_types.py    (pydantic v2 source)
        schemas/gen/asyncapi.yaml          (AsyncAPI 3.0 projection)

Supports exactly the constrained JSON-Schema subset used by the AEP registry
(AEP-0002 §5): objects of string/integer/number/boolean/enum/nested-object/array
members, plus primitive union type lists ("number" added with AEP-0006's
field_spec.min/max). Validation-only keywords (if/then, $comment) are passed
through untyped - they refine validity, not the type surface. Anything else fails
loudly - extend the generator in the same change that extends the schema subset.

Deterministic: identical input produces byte-identical output (CI diff gate).
Generated files are never edited by hand.
"""
from __future__ import annotations
import json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
SCHEMAS = os.path.dirname(HERE)
GEN_TS = os.path.join(SCHEMAS, "gen", "ts")
GEN_PY = os.path.join(SCHEMAS, "gen", "python")
GEN_ROOT = os.path.join(SCHEMAS, "gen")

HEADER = "GENERATED by schemas/codegen/generate.py - DO NOT EDIT (CI enforces: regenerate instead)"


def load(path):
    with open(path) as f:
        return json.load(f)


def pascal(name: str) -> str:
    return "".join(p.capitalize() for tok in name.split(".") for p in tok.split("_"))


def snake(name: str) -> str:
    return name.replace(".", "_").replace("-", "_")


def is_ident(name: str) -> bool:
    return name.replace("_", "a").isalnum() and not name[0].isdigit() and "." not in name


# YAML 1.1 words a bare scalar must not spell (booleans/null); everything the
# charset below allows is otherwise unambiguous as a plain scalar.
_YAML_WORDS = {"true", "false", "null", "yes", "no", "on", "off", "y", "n"}


def yaml_scalar(s: str) -> str:
    """Emit a string as a YAML scalar: plain when unambiguously safe,
    JSON-quoted otherwise (a double-quoted JSON string is valid YAML).
    Registry type names are plain-safe today, so current output is
    byte-identical; this protects the unquoted emitters (name/title)
    against any future name that needs quoting. Always-quoted fields
    (summary) stay on json.dumps."""
    if re.fullmatch(r"[A-Za-z_][A-Za-z0-9._-]*", s) and s.lower() not in _YAML_WORDS:
        return s
    return json.dumps(s)


class Gen:
    """Walks one payload schema once, accumulating named sub-interfaces/models."""

    def __init__(self, root_name: str):
        self.root = root_name
        self.ts_ifaces: list[tuple[str, list[str]]] = []   # (name, lines)
        self.py_models: list[tuple[str, list[str]]] = []

    # ---- single-pass type expression: returns (ts_expr, py_expr) ----------
    def expr(self, name: str, sch: dict, path: str = "") -> tuple[str, str]:
        if "enum" in sch:
            lits = ", ".join(json.dumps(v) for v in sch["enum"])
            return (" | ".join(json.dumps(v) for v in sch["enum"]), f"Literal[{lits}]")
        t = sch.get("type")
        if isinstance(t, list):
            pairs = [self.expr(name, {**sch, "type": x}, path) for x in t]
            return (" | ".join(p[0] for p in pairs), " | ".join(p[1] for p in pairs))
        if t == "string":
            return ("string", "str")
        if t == "integer":
            return ("number", "int")
        if t == "number":
            # JSON has one number type: pydantic v2 lax-coerces int wire
            # values into `float` fields (1 -> 1.0 on a round-trip) and
            # integral floats into `int` fields; TS `number` covers both.
            # Emitters own the int-vs-float distinction on the wire.
            return ("number", "float")
        if t == "boolean":
            return ("boolean", "bool")
        if t == "array":
            ts_i, py_i = self.expr(name + "Item", sch.get("items", {}), path + "[]")
            ts_arr = f"({ts_i})[]" if ("|" in ts_i) else f"{ts_i}[]"
            return (ts_arr, f"list[{py_i}]")
        if t == "object":
            if "properties" not in sch:
                return ("Record<string, unknown>", "dict[str, Any]")
            self.emit_object(name, sch, path)
            return (name, name)
        raise SystemExit(
            f"unsupported schema construct under {self.root} at {path or '<root>'}: {sch}")

    # ---- object emission (called exactly once per named object) -----------
    def emit_object(self, name: str, sch: dict, path: str = ""):
        req = set(sch.get("required", []))
        ts_lines, py_lines = [], []
        for prop, psch in sch["properties"].items():
            sub = name + pascal(prop) if prop.replace("_", "").isalnum() else name + pascal(snake(prop))
            ts_t, py_t = self.expr(sub, psch, f"{path}.{prop}" if path else prop)
            cap = psch.get("x-aep-capture")
            if cap and cap != "metadata":
                ts_lines.append(f"  /** capture >= {cap} */")
            key = prop if is_ident(prop) else json.dumps(prop)
            opt = "" if prop in req else "?"
            ts_lines.append(f"  {key}{opt}: {ts_t};")
            pyname = snake(prop)
            alias = f", alias={json.dumps(prop)}" if pyname != prop else ""
            note = f"  # capture >= {cap}" if cap and cap != "metadata" else ""
            if prop in req:
                if alias:
                    py_lines.append(f"    {pyname}: {py_t} = Field(...{alias}){note}")
                else:
                    py_lines.append(f"    {pyname}: {py_t}{note}")
            else:
                py_lines.append(f"    {pyname}: {py_t} | None = Field(None{alias}){note}")
        if not sch["properties"]:
            py_lines.append("    pass")
        self.ts_ifaces.append((name, ts_lines))
        self.py_models.append((name, py_lines))


def main():
    envelope = load(os.path.join(SCHEMAS, "aep-event.schema.json"))
    severity = load(os.path.join(SCHEMAS, "registry", "severity.json"))
    capture = load(os.path.join(SCHEMAS, "registry", "capture.json"))
    registry = load(os.path.join(SCHEMAS, "registry", "types.json"))

    types = registry["types"]
    with_schema = [t for t in types if t["schema"]]

    # ---------------- TypeScript ----------------
    ts: list[str] = [f"// {HEADER}", ""]
    ts.append("export type Severity = " + " | ".join(json.dumps(s) for s in severity["order"]) + ";")
    ts.append("export type Capture = " + " | ".join(json.dumps(c) for c in capture["order"]) + ";")
    ts.append("")
    ts.append("/** AEP-0001 §5 envelope: 16 context attributes + data. Extension attributes allowed. */")
    ts.append("export interface AepEvent {")
    env_req = set(envelope["required"])
    for prop, psch in envelope["properties"].items():
        if "const" in psch:
            t = json.dumps(psch["const"])
        elif prop == "severity":
            t = "Severity"
        elif prop == "capture":
            t = "Capture"
        elif prop == "data":
            t = "Record<string, unknown>"
        elif psch.get("type") in ("integer", "number"):
            t = "number"
        else:
            t = "string"
        opt = "" if prop in env_req else "?"
        ts.append(f"  {prop}{opt}: {t};")
    ts.append("  [extension: string]: unknown;")
    ts.append("}")
    ts.append("")

    payload_map: list[tuple[str, str]] = []
    for t in with_schema:
        sch = load(os.path.join(SCHEMAS, "types", t["schema"]))
        g = Gen(pascal(t["type"]) + "Data")
        g.emit_object(g.root, {"properties": sch.get("properties", {}), "required": sch.get("required", [])})
        for name, lines in g.ts_ifaces:
            ts.append(f"export interface {name} {{")
            ts.extend(lines if lines else [])
            ts.append("}")
            ts.append("")
        payload_map.append((t["type"], g.root))

    ts.append("export interface AepPayloadMap {")
    for wire, iface in payload_map:
        ts.append(f"  {json.dumps(wire)}: {iface};")
    ts.append("}")
    ts.append("")
    ts.append("export const AEP_CORE_TYPES = [")
    for t in types:
        ts.append(f"  {json.dumps(t['type'])},")
    ts.append("] as const;")
    ts.append("export type AepCoreType = (typeof AEP_CORE_TYPES)[number];")
    ts.append("")
    ts.append("export const AEP_MANDATORY_TYPES: readonly AepCoreType[] = [")
    for t in types:
        if t["status"] == "mandatory":
            ts.append(f"  {json.dumps(t['type'])},")
    ts.append("];")
    ts.append("")

    # ---------------- Python / pydantic ----------------
    py: list[str] = [
        f"# {HEADER}",
        "from __future__ import annotations",
        "",
        "from typing import Any, Literal",
        "",
        "from pydantic import BaseModel, ConfigDict, Field",
        "",
        "",
        "Severity = Literal[" + ", ".join(json.dumps(s) for s in severity["order"]) + "]",
        "Capture = Literal[" + ", ".join(json.dumps(c) for c in capture["order"]) + "]",
        "",
        "",
        "class AepEvent(BaseModel):",
        '    """AEP-0001 §5 envelope: 16 context attributes + data (extensions allowed)."""',
        "",
        "    model_config = ConfigDict(extra=\"allow\", populate_by_name=True)",
        "",
    ]
    for prop, psch in envelope["properties"].items():
        if "const" in psch:
            t = f"Literal[{json.dumps(psch['const'])}]"
        elif prop == "severity":
            t = "Severity"
        elif prop == "capture":
            t = "Capture"
        elif prop == "data":
            t = "dict[str, Any]"
        elif psch.get("type") == "integer":
            t = "int"
        elif psch.get("type") == "number":
            t = "float"  # int wire values lax-coerce (see Gen.expr's number note)
        else:
            t = "str"
        if prop in env_req:
            py.append(f"    {prop}: {t}")
        else:
            py.append(f"    {prop}: {t} | None = None")
    py.append("")
    py.append("")

    py_payload_entries: list[tuple[str, str]] = []
    for t in with_schema:
        sch = load(os.path.join(SCHEMAS, "types", t["schema"]))
        g = Gen(pascal(t["type"]) + "Data")
        g.emit_object(g.root, {"properties": sch.get("properties", {}), "required": sch.get("required", [])})
        for name, lines in g.py_models:
            py.append(f"class {name}(BaseModel):")
            py.append("    model_config = ConfigDict(extra=\"allow\", populate_by_name=True)")
            py.append("")
            py.extend(lines)
            py.append("")
            py.append("")
        py_payload_entries.append((t["type"], g.root))

    py.append("PAYLOAD_MODELS: dict[str, type[BaseModel]] = {")
    for wire, model in py_payload_entries:
        py.append(f"    {json.dumps(wire)}: {model},")
    py.append("}")
    py.append("")
    py.append("AEP_CORE_TYPES: tuple[str, ...] = (")
    for t in types:
        py.append(f"    {json.dumps(t['type'])},")
    py.append(")")
    py.append("")
    py.append("AEP_MANDATORY_TYPES: tuple[str, ...] = (")
    for t in types:
        if t["status"] == "mandatory":
            py.append(f"    {json.dumps(t['type'])},")
    py.append(")")
    py.append("")

    # ---------------- AsyncAPI 3.0 projection ----------------
    aa: list[str] = [
        f"# {HEADER}",
        "asyncapi: 3.0.0",
        "info:",
        "  title: AEP - Agent Events Protocol (working title)",
        "  version: \"0.1\"",
        "  description: >-",
        "    AsyncAPI projection of the AEP 0.1 registry. The JSON Schema registry",
        "    (schemas/) is the source of truth; this catalog is generated.",
        "defaultContentType: application/json",
        "channels:",
        "  events:",
        "    address: /events",
        "    description: AEP event stream (all bindings carry the identical envelope).",
        "    messages:",
    ]
    for t in types:
        if t["status"] == "reserved":
            continue
        key = snake(t["type"])
        aa.append(f"      {key}:")
        aa.append(f"        $ref: '#/components/messages/{key}'")
    aa.append("components:")
    aa.append("  messages:")
    for t in types:
        if t["status"] == "reserved":
            continue
        key = snake(t["type"])
        aa.append(f"    {key}:")
        aa.append(f"      name: {yaml_scalar(t['type'])}")
        aa.append(f"      title: {yaml_scalar(t['type'])}")
        aa.append(f"      summary: {json.dumps(t['summary'])}")
        aa.append("      payload:")
        aa.append("        schemaFormat: application/schema+json;version=draft-2020-12")
        if t["schema"]:
            aa.append(f"        schema:")
            aa.append(f"          $ref: '../types/{t['schema']}'")
        else:
            aa.append("        schema:")
            aa.append("          type: object")

    os.makedirs(GEN_TS, exist_ok=True)
    os.makedirs(GEN_PY, exist_ok=True)
    with open(os.path.join(GEN_TS, "aep-types.ts"), "w") as f:
        f.write("\n".join(ts).rstrip() + "\n")
    with open(os.path.join(GEN_PY, "aep_types.py"), "w") as f:
        f.write("\n".join(py).rstrip() + "\n")
    with open(os.path.join(GEN_ROOT, "asyncapi.yaml"), "w") as f:
        f.write("\n".join(aa).rstrip() + "\n")
    # SDK packages (the SDK type surface is generated, never handwritten).
    # The SDKs live in their own repositories and carry a sync check that
    # regenerates their committed types from this repo's schemas at a pinned
    # revision (see each SDK repo's CI). When this generator is run inside a
    # tree that also contains those packages, it mirrors the output into them;
    # in the standalone standard repo there is no sibling sdk/, so this is a
    # no-op and the diff gate covers only the in-repo gen/.
    sdk_root = os.path.join(SCHEMAS, "..", "sdk")
    if os.path.isdir(sdk_root):
        sdk_ts = os.path.join(sdk_root, "ts", "src", "gen")
        sdk_py = os.path.join(sdk_root, "python", "aep_sdk", "gen")
        os.makedirs(sdk_ts, exist_ok=True)
        os.makedirs(sdk_py, exist_ok=True)
        with open(os.path.join(sdk_ts, "aep-types.ts"), "w") as f:
            f.write("\n".join(ts).rstrip() + "\n")
        with open(os.path.join(sdk_py, "aep_types.py"), "w") as f:
            f.write("\n".join(py).rstrip() + "\n")
        print("generated: gen/ts/aep-types.ts, gen/python/aep_types.py, gen/asyncapi.yaml, "
              "sdk/ts/src/gen/aep-types.ts, sdk/python/aep_sdk/gen/aep_types.py")
    else:
        print("generated: gen/ts/aep-types.ts, gen/python/aep_types.py, gen/asyncapi.yaml")


if __name__ == "__main__":
    main()
